import { jsPDF } from 'jspdf';
import { WorkoutPlan, Language } from '../types';
import { translateExerciseName, translateMuscle, translateDayName } from '../translations';

// Simple Cyrillic transliteration function to ensure Russian text is fully readable 
// in standard jsPDF Helvetica fonts (which do not support native Cyrillic).
function transliterate(text: string): string {
  const rus = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя".split("");
  const lat = [
    "A","B","V","G","D","E","Yo","Zh","Z","I","Y","K","L","M","N","O","P","R","S","T","U","F","Kh","Ts","Ch","Sh","Shch","","Y","","E","Yu","Ya",
    "a","b","v","g","d","e","yo","zh","z","i","y","k","l","m","n","o","p","r","s","t","u","f","kh","ts","ch","sh","shch","","y","","e","yu","ya"
  ];
  return text
    .split("")
    .map(char => {
      const idx = rus.indexOf(char);
      return idx > -1 ? lat[idx] : char;
    })
    .join("");
}

export function exportWorkoutToPdf(workout: WorkoutPlan, lang: Language) {
  // Initialize standard A4 PDF (210mm x 297mm)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const isRu = lang === 'ru';
  
  // Clean titles & text based on language
  const titleText = isRu 
    ? transliterate("План тренировок") 
    : lang === 'et' 
      ? "Treeningkava" 
      : "Workout Training Plan";
      
  const planName = isRu ? transliterate(workout.name || "Моя тренировка") : (workout.name || "My Workout Plan");
  
  // Page boundaries & layout params
  const marginX = 20;
  const pageHeight = 297;
  const pageWidth = 210;
  const contentWidth = pageWidth - (marginX * 2); // 170mm
  
  let currentY = 25;

  const checkPageBreak = (neededHeight: number) => {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage();
      currentY = 25;
      drawPageDecorations();
    }
  };

  const drawPageDecorations = () => {
    // Header thin accent band
    doc.setFillColor(30, 41, 59); // Slate 800
    doc.rect(0, 0, pageWidth, 4, 'F');

    // Footer
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(
      lang === 'et' ? "Genereeritud Ruumilise Treeningmootori abil" : isRu ? transliterate("Сгенерировано в Пространственном Тренажере") : "Generated by Spatial Training Engine",
      marginX,
      pageHeight - 10
    );

    const pageCount = doc.getNumberOfPages();
    doc.text(`${pageCount}`, pageWidth - marginX - 5, pageHeight - 10);
  };

  // Draw first page decoration
  drawPageDecorations();

  // Header Banner
  doc.setFillColor(15, 23, 42); // Deep Slate 900
  doc.rect(marginX, currentY, contentWidth, 32, 'F');

  // Title inside banner
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(titleText.toUpperCase(), marginX + 8, currentY + 11);

  // Subtitle / Plan Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(132, 204, 22); // Lime 500
  doc.text(planName, marginX + 8, currentY + 20);

  // Total Duration / Date info
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // Slate 400
  const dateStr = new Date().toLocaleDateString(lang === 'et' ? 'et-EE' : lang === 'ru' ? 'ru-RU' : 'en-US');
  const durationLabel = lang === 'et' ? "Kestus" : isRu ? transliterate("Длительность") : "Duration";
  const durationText = `${durationLabel}: ~${workout.totalDurationMinutes || 60} min | ${dateStr}`;
  doc.text(durationText, marginX + 8, currentY + 26);

  currentY += 40;

  // Render each Day
  workout.days.forEach((day, dayIdx) => {
    checkPageBreak(18);

    // Day Header Strip
    doc.setFillColor(30, 41, 59); // Slate 800
    doc.rect(marginX, currentY, contentWidth, 10, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    
    const dayPrefix = lang === 'et' ? "PÄEV" : isRu ? transliterate("ДЕНЬ") : "DAY";
    const translatedDayName = translateDayName(day.name, dayIdx, lang);
    const dayTitle = `${dayPrefix} ${dayIdx + 1}: ${isRu ? transliterate(translatedDayName) : translatedDayName}`;
    doc.text(dayTitle, marginX + 5, currentY + 6.5);

    currentY += 14;

    if (!day.exercises || day.exercises.length === 0) {
      checkPageBreak(12);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139); // Slate 500
      const emptyText = lang === 'et' ? "Harjutusi pole kavas" : isRu ? transliterate("Нет упражнений в плане") : "No exercises in this day";
      doc.text(emptyText, marginX + 5, currentY);
      currentY += 10;
      return;
    }

    // Render Exercises for the Day
    day.exercises.forEach((ex, exIdx) => {
      // Approximate height needed: 22mm for the block, plus wrapping space for notes
      const translatedName = translateExerciseName(ex.name, lang);
      const translatedMuscle = translateMuscle(ex.targetMuscle, lang);
      const exName = isRu ? transliterate(translatedName) : translatedName;
      const targetMuscle = isRu ? transliterate(translatedMuscle) : translatedMuscle;
      const notes = ex.notes ? (isRu ? transliterate(ex.notes) : ex.notes) : '';

      // Let's compute text splitting for notes
      const notesWidth = contentWidth - 10;
      const splitNotes = notes ? doc.splitTextToSize(notes, notesWidth) : [];
      const notesHeight = splitNotes.length * 4.5;
      const blockHeight = 16 + (notes ? notesHeight + 4 : 0);

      checkPageBreak(blockHeight + 4);

      // Light backing rectangle for exercise
      doc.setFillColor(248, 250, 252); // Gray 50
      doc.rect(marginX, currentY, contentWidth, blockHeight, 'F');
      
      // Left border indicator in custom gray/slate
      doc.setFillColor(203, 213, 225); // Slate 300
      doc.rect(marginX, currentY, 1.5, blockHeight, 'F');

      // Exercise numbering & Name
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42); // Slate 900
      doc.text(`${exIdx + 1}. ${exName}`, marginX + 5, currentY + 6);

      // Sets, Reps and Muscle Group details
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105); // Slate 600

      const setsLabel = lang === 'et' ? "seeriat" : isRu ? transliterate("подхода") : "sets";
      const repsLabel = lang === 'et' ? "kordust" : isRu ? transliterate("повторений") : "reps";
      const muscleLabel = lang === 'et' ? "lihasrühm" : isRu ? transliterate("целевая мышца") : "target muscle";
      const detailText = `${ex.sets} ${setsLabel} x ${ex.reps} ${repsLabel}  |  ${muscleLabel}: ${targetMuscle}`;
      doc.text(detailText, marginX + 5, currentY + 11);

      // Instructions / Notes (if present)
      if (notes) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139); // Slate 500
        
        let notesY = currentY + 16;
        splitNotes.forEach((line: string) => {
          doc.text(line, marginX + 5, notesY);
          notesY += 4.5;
        });
      }

      currentY += blockHeight + 3;
    });

    currentY += 5; // Spacing between days
  });

  // Save/Download the PDF
  const filename = `${workout.name.toLowerCase().replace(/\s+/g, '_')}_plan.pdf`;
  doc.save(filename);
}
